import React, { useEffect, useMemo, useState } from 'react';
import { BarChart3, Bot, CheckCircle2, CircleDollarSign, ClipboardList, MessageCircle, PauseCircle, PlayCircle, RefreshCcw, Search, Send, Settings, Tags, Trash2, UserCheck, Workflow } from 'lucide-react';

const STATUS = [
  { id: 'novo', label: 'Novo' },
  { id: 'ativo', label: 'Ativo' },
  { id: 'qualificado', label: 'Qualificado' },
  { id: 'proposta', label: 'Proposta' },
  { id: 'comprador', label: 'Comprador' },
  { id: 'perdido', label: 'Perdido' }
];
const API = '';
const formatTime = (v) => (v ? new Intl.DateTimeFormat('pt-BR', { hour: '2-digit', minute: '2-digit', day: '2-digit', month: '2-digit' }).format(new Date(v)) : '');
const request = async (path, options = {}) => { const r = await fetch(`${API}${path}`, { headers: { 'Content-Type': 'application/json', ...(options.headers || {}) }, ...options }); const d = await r.json().catch(() => ({})); if (!r.ok) throw new Error(d.error || 'Erro na operação.'); return d; };

export default function App() {
  const [state, setState] = useState(null); const [tab, setTab] = useState('inbox'); const [selectedId, setSelectedId] = useState(null); const [query, setQuery] = useState('');
  const [simulateText, setSimulateText] = useState('Quero saber o preço'); const [replyText, setReplyText] = useState(''); const [tagDraft, setTagDraft] = useState('');
  const [flowDraft, setFlowDraft] = useState({ name: '', keywords: '', response: '' }); const [editingFlowId, setEditingFlowId] = useState(null); const [statusMessage, setStatusMessage] = useState('');
  const load = async () => { const d = await request('/api/state'); setState(d); if (!selectedId && d.conversations?.length) setSelectedId(d.conversations[0].id); };
  useEffect(() => { load().catch((e) => setStatusMessage(e.message)); const i = setInterval(() => load().catch(() => null), 4000); return () => clearInterval(i); }, []);
  const conversations = state?.conversations || []; const selected = conversations.find((c) => c.id === selectedId) || conversations[0];
  const filteredConversations = useMemo(() => conversations.filter((c) => [c.name, c.phone, c.source, c.status, ...(c.tags || [])].join(' ').toLowerCase().includes(query.trim().toLowerCase())).sort((a,b)=>(b.unread||0)-(a.unread||0)||new Date(b.updatedAt)-new Date(a.updatedAt)), [conversations, query]);
  const mutate = async (action, okMsg) => { try { const result = await action(); setState(await request('/api/state')); if (result?.conversation?.id) setSelectedId(result.conversation.id); setStatusMessage(okMsg || 'Operação concluída.'); } catch (e) { setStatusMessage(e.message); } };
  if (!state) return <main className="loading-screen"><div className="spinner" /><p>Carregando WabaFlow Inbox v6...</p></main>;
  return <div className="app-shell"><header className="topbar"><div><span className="eyebrow">v6 Cloudflare-ready (simulado)</span><h1>WabaFlow Inbox v6</h1></div><div className="topbar-actions"><span className={`mode-badge ${state.settings?.mode === 'cloud_ready' ? 'off' : 'on'}`}>{state.settings?.mode === 'cloud_ready' ? 'Modo cloud_ready' : 'Modo simulado'}</span><button className="ghost-button" onClick={load}><RefreshCcw size={16}/> Atualizar</button></div></header>
  {statusMessage && <div className="toast" onClick={() => setStatusMessage('')}>{statusMessage}</div>}
  <nav className="tabs">{[['inbox','Inbox',MessageCircle],['funnel','Funil',BarChart3],['flows','Fluxos',Workflow],['events','Eventos',ClipboardList],['settings','Configurações',Settings]].map(([id,label,Icon])=> <button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon size={17}/> {label}</button>)}</nav>
  {tab==='inbox' && <section className="inbox-grid"><aside className="conversation-list card"><div className="search-box"><Search size={16}/><input placeholder="Buscar lead, telefone, tag ou status" value={query} onChange={(e)=>setQuery(e.target.value)}/></div><div className="list-scroll">{filteredConversations.map((conv)=><button key={conv.id} className={`conversation-item ${selected?.id===conv.id?'selected':''}`} onClick={()=>setSelectedId(conv.id)}><div className="avatar">{conv.name?.slice(0,1)||'L'}</div><div className="conversation-summary"><strong>{conv.name} {!!conv.unread && <small>({conv.unread})</small>}</strong><span>{conv.messages?.at(-1)?.text || 'Sem mensagens'}</span><div className="mini-row"><small>{formatTime(conv.updatedAt)}</small><small className={`status-dot ${conv.status}`}>{conv.status}</small></div></div></button>)} </div></aside>
  <main className="chat-panel card"><div className="simulate-bar"><input value={simulateText} onChange={(e)=>setSimulateText(e.target.value)} placeholder="Texto para simular entrada de cliente"/><button onClick={()=>selected&&mutate(()=>request('/api/simulate/current-message',{method:'POST',body:JSON.stringify({conversationId:selected.id,text:simulateText})}),'Mensagem adicionada.')}>Mensagem atual</button><button className="primary" onClick={()=>mutate(()=>request('/api/simulate/new-lead',{method:'POST',body:JSON.stringify({text:simulateText})}),'Novo lead criado.')}>Novo lead</button></div>{selected ? <><div className="chat-header"><div><h2>{selected.name}</h2><span>{selected.phone} · {selected.source}</span></div><button className={selected.humanMode?'danger-soft':'ghost-button'} onClick={()=>mutate(()=>request(`/api/conversations/${selected.id}/human-mode`,{method:'PATCH',body:JSON.stringify({humanMode:!selected.humanMode})}), selected.humanMode?'Automação retomada.':'Atendimento humano assumido.')}>{selected.humanMode?<PauseCircle size={16}/>:<PlayCircle size={16}/>} {selected.humanMode?'Humano assumiu':'Automação liberada'}</button></div><div className="messages">{(selected.messages||[]).map((m)=><div key={m.id} className={`message ${m.direction}`}><p>{m.text}</p><small>{formatTime(m.createdAt)} {m.meta?.flowName?`· ${m.meta.flowName}`:''}</small></div>)}</div><div className="reply-box"><input value={replyText} onChange={(e)=>setReplyText(e.target.value)} placeholder="Responder manualmente" onKeyDown={(e)=>e.key==='Enter'&&mutate(()=>request(`/api/conversations/${selected.id}/send`,{method:'POST',body:JSON.stringify({text:replyText})}),'Resposta enviada.')}/><button className="primary" onClick={()=>{ const t=replyText; setReplyText(''); mutate(()=>request(`/api/conversations/${selected.id}/send`,{method:'POST',body:JSON.stringify({text:t})}),'Resposta enviada.'); }}><Send size={16}/> Enviar</button></div></> : <div className="empty-state"><Bot size={36}/> Crie um novo lead simulado para começar.</div>}</main>
  <aside className="lead-panel card">{selected && <><h3>Painel do lead</h3><label>Status comercial</label><select value={selected.status} onChange={(e)=>mutate(()=>request(`/api/conversations/${selected.id}/status`,{method:'PATCH',body:JSON.stringify({status:e.target.value})}),'Status atualizado.')}>{STATUS.map((s)=><option key={s.id} value={s.id}>{s.label}</option>)}</select><label>Tags</label><div className="tag-list">{(selected.tags||[]).map((tag)=><button key={tag} onClick={()=>mutate(()=>request(`/api/conversations/${selected.id}/tags`,{method:'PATCH',body:JSON.stringify({tags:selected.tags.filter((t)=>t!==tag)})}),'Tag removida.')}>{tag} ×</button>)}</div><div className="inline-form"><input value={tagDraft} onChange={(e)=>setTagDraft(e.target.value)} placeholder="Nova tag"/><button onClick={()=>{ const tags=[...(selected.tags||[]),tagDraft.trim()].filter(Boolean); setTagDraft(''); mutate(()=>request(`/api/conversations/${selected.id}/tags`,{method:'PATCH',body:JSON.stringify({tags})}),'Tag adicionada.'); }}><Tags size={15}/></button></div><label>Observação interna</label><textarea defaultValue={selected.notes} onBlur={(e)=>mutate(()=>request(`/api/conversations/${selected.id}/notes`,{method:'PATCH',body:JSON.stringify({notes:e.target.value})}),'Observação salva.')}/></>}</aside></section>}
  {tab==='funnel' && <section className="stack"><div className="metrics-grid"><MetricCard label="Conversas" value={state.metrics?.totalConversations||0} icon={<MessageCircle size={20}/>}/><MetricCard label="Compradores" value={state.metrics?.buyerCount||0} icon={<CheckCircle2 size={20}/>}/><MetricCard label="Conversão funil" value={`${state.metrics?.funnelConversionRate||0}%`} icon={<CircleDollarSign size={20}/>}/><MetricCard label="Proposta > Compra" value={`${state.metrics?.proposalToBuyerRate||0}%`} icon={<UserCheck size={20}/>}/></div></section>}
  {tab==='flows' && <section className="two-column"><div className="card form-card"><h2>{editingFlowId?'Editar fluxo':'Criar fluxo'}</h2><input value={flowDraft.name} onChange={(e)=>setFlowDraft({...flowDraft,name:e.target.value})} placeholder="Nome"/><input value={flowDraft.keywords} onChange={(e)=>setFlowDraft({...flowDraft,keywords:e.target.value})} placeholder="Palavras-chave"/><textarea value={flowDraft.response} onChange={(e)=>setFlowDraft({...flowDraft,response:e.target.value})} placeholder="Resposta"/><button className="primary" onClick={()=>mutate(()=>editingFlowId?request(`/api/flows/${editingFlowId}`,{method:'PUT',body:JSON.stringify({name:flowDraft.name,keywords:flowDraft.keywords.split(',').map((i)=>i.trim()).filter(Boolean),response:flowDraft.response})}):request('/api/flows',{method:'POST',body:JSON.stringify({name:flowDraft.name,keywords:flowDraft.keywords.split(',').map((i)=>i.trim()).filter(Boolean),response:flowDraft.response})}),'Fluxo salvo.')}>Salvar</button></div><div className="card list-card">{(state.flows||[]).map((f)=><div className="flow-item" key={f.id}><div><strong>{f.name}</strong><p>{f.response}</p></div><div className="flow-actions"><button onClick={()=>mutate(()=>request(`/api/flows/${f.id}`,{method:'PUT',body:JSON.stringify({...f,active:!f.active})}),'Fluxo atualizado.')}>{f.active?'Pausar':'Ativar'}</button><button onClick={()=>{setEditingFlowId(f.id);setFlowDraft({name:f.name,keywords:(f.keywords||[]).join(', '),response:f.response});}}>Editar</button><button className="danger-soft" onClick={()=>mutate(()=>request(`/api/flows/${f.id}`,{method:'DELETE'}),'Fluxo excluído.')}><Trash2 size={15}/> Excluir</button></div></div>)}</div></section>}
  {tab==='events' && <section className="card events-card"><h2>Histórico</h2><div className="event-list">{(state.events||[]).map((e)=><div className="event-item" key={e.id}><span className="event-type">{e.type}</span><strong>{e.label}</strong><small>{formatTime(e.createdAt)}</small></div>)}</div></section>}
  {tab==='settings' && <section className="two-column"><div className="card form-card"><h2>Configurações v6</h2><label className="switch-row"><input type="checkbox" checked={state.settings?.autoReplyEnabled} onChange={(e)=>mutate(()=>request('/api/settings',{method:'PATCH',body:JSON.stringify({autoReplyEnabled:e.target.checked})}),'Configuração salva.')}/> Automação global ativa</label><label className="switch-row"><input type="checkbox" checked={state.settings?.mode==='cloud_ready'} onChange={(e)=>mutate(()=>request('/api/settings',{method:'PATCH',body:JSON.stringify({mode:e.target.checked?'cloud_ready':'simulated'})}),'Modo atualizado.')}/> Preparar para integração real (sem tokens)</label></div><div className="card list-card"><h2>Métricas</h2><p>Mensagens de entrada: {state.metrics?.inboundMessages||0}</p><p>Mensagens de saída: {state.metrics?.outboundMessages||0}</p><p>Média por conversa: {state.metrics?.avgMessagesPerConversation||0}</p></div></section>}
  </div>;
}
function MetricCard({ label, value, icon }) { return <div className="metric-card"><div>{icon}</div><strong>{value}</strong><span>{label}</span></div>; }
